name: Tarefa Agendada - API 1 Health Check

on:
  schedule:
    - cron: "3,13,23,33,43,53 * * * *"
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer requisição para minha API
        run: |
          date
          curl --fail --show-error --silent --max-time 120 \
            https://springboot-rest-2575.onrender.com/

